// Copyright 2020 Fortinet, Inc. All rights reserved.
package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/provider"
	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// Ensure FortisaseProvider satisfies various provider interfaces.
var _ provider.Provider = &FortisaseProvider{}

// FortisaseProvider defines the provider implementation.
type FortisaseProvider struct {
	// version is set to the provider version on release, "dev" when the
	// provider is built and ran locally, and "test" when running acceptance
	// testing.
	version string
}

// FortisaseProviderModel describes the provider data model.
type FortisaseProviderModel struct {
	Username     types.String `tfsdk:"username"`
	Password     types.String `tfsdk:"password"`
	AccessToken  types.String `tfsdk:"access_token"`
	RefreshToken types.String `tfsdk:"refresh_token"`
}

func (p *FortisaseProvider) Metadata(ctx context.Context, req provider.MetadataRequest, resp *provider.MetadataResponse) {
	resp.TypeName = "fortisase"
}

func (p *FortisaseProvider) Schema(ctx context.Context, req provider.SchemaRequest, resp *provider.SchemaResponse) {
	resp.Schema = schema.Schema{
		Attributes: map[string]schema.Attribute{
			"username": schema.StringAttribute{
				MarkdownDescription: "The username of API user.",
				Optional:            true,
			},
			"password": schema.StringAttribute{
				MarkdownDescription: "The password of API user.",
				Optional:            true,
			},
			"access_token": schema.StringAttribute{
				MarkdownDescription: "The access token of API user.",
				Optional:            true,
			},
			"refresh_token": schema.StringAttribute{
				MarkdownDescription: "The refresh token of API user.",
				Optional:            true,
			},
		},
	}
}

func (p *FortisaseProvider) Configure(ctx context.Context, req provider.ConfigureRequest, resp *provider.ConfigureResponse) {
	var data FortisaseProviderModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	config := Config{
		Username:     data.Username.ValueString(),
		Password:     data.Password.ValueString(),
		AccessToken:  data.AccessToken.ValueString(),
		RefreshToken: data.RefreshToken.ValueString(),
	}

	sdkClient, err := config.CreateClient()
	if err != nil {
		resp.Diagnostics.AddError(
			fmt.Sprintf("Error to create client: %v", err),
			"",
		)
	}
	resp.DataSourceData = sdkClient
	resp.ResourceData = sdkClient
	resp.EphemeralResourceData = sdkClient
}
func (p *FortisaseProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		newResourceAuthFssoAgent,
		newResourceAuthFssoAgents,
		newResourceAuthLdapServer,
		newResourceAuthLdapServers,
		newResourceAuthRadiusServer,
		newResourceAuthRadiusServers,
		newResourceAuthSslvpnSamlServer,
		newResourceAuthSwgSamlServer,
		newResourceAuthUser,
		newResourceAuthUserGroup,
		newResourceAuthUserGroups,
		newResourceAuthUsers,
		newResourceAuthVpnSamlServer,
		newResourceDemCustomSaasApp,
		newResourceDemCustomSaasApps,
		newResourceDemSpaApplication,
		newResourceDemSpaApplications,
		newResourceEndpointConnectionProfile,
		newResourceEndpointConnectionProfiles,
		newResourceEndpointFssoProfile,
		newResourceEndpointFssoProfiles,
		newResourceEndpointGroupAdUserProfile,
		newResourceEndpointGroupAdUserProfiles,
		newResourceEndpointGroupInvitationCode,
		newResourceEndpointGroupInvitationCodes,
		newResourceEndpointMdmIntegration,
		newResourceEndpointOnNetRule,
		newResourceEndpointOnNetRules,
		newResourceEndpointPolicies,
		newResourceEndpointPoliciesClone,
		newResourceEndpointPolicy,
		newResourceEndpointPolicyClone,
		newResourceEndpointProfile,
		newResourceEndpointProfileClone,
		newResourceEndpointProtectionProfile,
		newResourceEndpointProtectionProfiles,
		newResourceEndpointSandboxProfile,
		newResourceEndpointSandboxProfiles,
		newResourceEndpointSettingProfile,
		newResourceEndpointSettingProfiles,
		newResourceEndpointZtnaProfile,
		newResourceEndpointZtnaProfiles,
		newResourceEndpointZtnaRule,
		newResourceEndpointZtnaRules,
		newResourceEndpointZtnaTag,
		newResourceEndpointZtnaTagRule,
		newResourceEndpointZtnaTags,
		newResourceEndpointsAccessProxyAuthorize,
		newResourceEndpointsAccessProxyDisconnect,
		newResourceEndpointsDisableManagement,
		newResourceEndpointsEnableManagement,
		newResourceInfraIpamSetting,
		newResourceInfraSecureWebGatewaySupplementaryData,
		newResourceInfraSsid,
		newResourceInfraSsids,
		newResourceNetworkDnsRule,
		newResourceNetworkDnsRules,
		newResourceNetworkHost,
		newResourceNetworkHostGroup,
		newResourceNetworkHostGroups,
		newResourceNetworkHosts,
		newResourceNetworkImplicitDnsRule,
		newResourceNetworkImplicitDnsRules,
		newResourcePrivateAccessNetworkConfiguration,
		newResourcePrivateAccessServiceConnection,
		newResourcePrivateAccessServiceConnectionAuth,
		newResourcePrivateAccessServiceConnectionRegionCost,
		newResourcePrivateAccessServiceConnections,
		newResourcePrivateAccessServiceConnectionsAuth,
		newResourcePrivateAccessServiceConnectionsRegionCost,
		newResourceSecurityAntivirusProfile,
		newResourceSecurityAppCustomSignature,
		newResourceSecurityAppCustomSignatures,
		newResourceSecurityApplicationControlProfile,
		newResourceSecurityCertLocalCaCert,
		newResourceSecurityCertLocalCaCerts,
		newResourceSecurityCertLocalCert,
		newResourceSecurityCertLocalCerts,
		newResourceSecurityCertRemoteCaCert,
		newResourceSecurityCertRemoteCaCerts,
		newResourceSecurityCertRemoteCert,
		newResourceSecurityCertRemoteCerts,
		newResourceSecurityDlpDictionaries,
		newResourceSecurityDlpDictionary,
		newResourceSecurityDlpExactDataMatch,
		newResourceSecurityDlpExactDataMatches,
		newResourceSecurityDlpFilePattern,
		newResourceSecurityDlpFilePatterns,
		newResourceSecurityDlpFingerprintDatabase,
		newResourceSecurityDlpFingerprintDatabases,
		newResourceSecurityDlpProfile,
		newResourceSecurityDlpSensor,
		newResourceSecurityDlpSensors,
		newResourceSecurityDnsFilterProfile,
		newResourceSecurityDomainThreatFeed,
		newResourceSecurityDomainThreatFeeds,
		newResourceSecurityEndpointToEndpointPolicies,
		newResourceSecurityEndpointToEndpointPoliciesClone,
		newResourceSecurityEndpointToEndpointPolicy,
		newResourceSecurityEndpointToEndpointPolicyClone,
		newResourceSecurityFileFilterProfile,
		newResourceSecurityFortiguardLocalCategories,
		newResourceSecurityFortiguardLocalCategory,
		newResourceSecurityHtmlTemplate,
		newResourceSecurityHtmlTemplateImage,
		newResourceSecurityInternalPolicies,
		newResourceSecurityInternalPoliciesClone,
		newResourceSecurityInternalPolicy,
		newResourceSecurityInternalPolicyClone,
		newResourceSecurityInternalProxyPolicy,
		newResourceSecurityInternalProxyPolicyClone,
		newResourceSecurityInternalReversePolicies,
		newResourceSecurityInternalReversePoliciesClone,
		newResourceSecurityInternalReversePolicy,
		newResourceSecurityInternalReversePolicyClone,
		newResourceSecurityIpThreatFeed,
		newResourceSecurityIpThreatFeeds,
		newResourceSecurityIpsCustomSignature,
		newResourceSecurityIpsCustomSignatures,
		newResourceSecurityIpsProfile,
		newResourceSecurityOnetimeSchedule,
		newResourceSecurityOnetimeSchedules,
		newResourceSecurityOutboundPolicies,
		newResourceSecurityOutboundPoliciesClone,
		newResourceSecurityOutboundPolicy,
		newResourceSecurityOutboundPolicyClone,
		newResourceSecurityOutboundProxyPolicy,
		newResourceSecurityOutboundProxyPolicyClone,
		newResourceSecurityPerIpTrafficShaper,
		newResourceSecurityPkiUser,
		newResourceSecurityPkiUsers,
		newResourceSecurityProfileGroup,
		newResourceSecurityProfileGroupClone,
		newResourceSecurityRecurringSchedule,
		newResourceSecurityRecurringSchedules,
		newResourceSecurityScheduleGroup,
		newResourceSecurityScheduleGroups,
		newResourceSecurityService,
		newResourceSecurityServiceGroup,
		newResourceSecurityServiceGroups,
		newResourceSecurityServices,
		newResourceSecuritySslSshProfile,
		newResourceSecurityTrafficShaper,
		newResourceSecurityTrafficShapingPolicy,
		newResourceSecurityUrlThreatFeed,
		newResourceSecurityUrlThreatFeeds,
		newResourceSecurityVideoFilterProfile,
		newResourceSecurityVideoFilterYoutubeKey,
		newResourceSecurityWebFilterProfile,
		newResourceSystemCertificate,
		newResourceUserSwgSessionsDeauth,
		newResourceUserVpnSessionsDeauth,
	}
}

func (p *FortisaseProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		newDatasourceAuthFssoAgent,
		newDatasourceAuthFssoAgents,
		newDatasourceAuthLdapServer,
		newDatasourceAuthLdapServers,
		newDatasourceAuthRadiusServer,
		newDatasourceAuthRadiusServers,
		newDatasourceAuthSslvpnSamlServer,
		newDatasourceAuthSwgSamlServer,
		newDatasourceAuthUserGroup,
		newDatasourceAuthUserGroups,
		newDatasourceAuthUser,
		newDatasourceAuthUsers,
		newDatasourceAuthVpnSamlServer,
		newDatasourceBrowserProvision,
		newDatasourceDemCustomSaasApp,
		newDatasourceDemCustomSaasApps,
		newDatasourceDemSpaApplication,
		newDatasourceDemSpaApplications,
		newDatasourceEndpointConnectionProfile,
		newDatasourceEndpointConnectionProfiles,
		newDatasourceEndpointFssoProfile,
		newDatasourceEndpointFssoProfiles,
		newDatasourceEndpointGroupAdUserProfile,
		newDatasourceEndpointGroupAdUserProfiles,
		newDatasourceEndpointGroupInvitationCode,
		newDatasourceEndpointGroupInvitationCodes,
		newDatasourceEndpointMdmIntegration,
		newDatasourceEndpointOnNetRule,
		newDatasourceEndpointOnNetRules,
		newDatasourceEndpointPolicy,
		newDatasourceEndpointPolicies,
		newDatasourceEndpointProfile,
		newDatasourceEndpointProtectionProfile,
		newDatasourceEndpointProtectionProfiles,
		newDatasourceEndpointSandboxProfile,
		newDatasourceEndpointSandboxProfiles,
		newDatasourceEndpointSettingProfile,
		newDatasourceEndpointSettingProfiles,
		newDatasourceEndpointZtnaProfile,
		newDatasourceEndpointZtnaProfiles,
		newDatasourceEndpointZtnaRule,
		newDatasourceEndpointZtnaRules,
		newDatasourceEndpointZtnaTagRule,
		newDatasourceEndpointZtnaTag,
		newDatasourceEndpointZtnaTags,
		newDatasourceEndpointsClientUserDetail,
		newDatasourceEndpointsClientUserDetails,
		newDatasourceEndpointsDetail,
		newDatasourceEndpointsDetails,
		newDatasourceEndpointsDonut,
		newDatasourceEndpointsEndpointsWithSoftware,
		newDatasourceEndpointsGroup,
		newDatasourceEndpointsGroups,
		newDatasourceEndpointsSoftwareOnClientUser,
		newDatasourceEndpointsSoftwareOnEndpoint,
		newDatasourceInfraDataTransfer,
		newDatasourceInfraExtender,
		newDatasourceInfraExtenders,
		newDatasourceInfraFortigate,
		newDatasourceInfraFortigates,
		newDatasourceInfraIpamSetting,
		newDatasourceInfraSecureWebGatewaySupplementaryData,
		newDatasourceInfraSsid,
		newDatasourceInfraSsids,
		newDatasourceNetworkBasicInternetService,
		newDatasourceNetworkBasicInternetServices,
		newDatasourceNetworkDnsRule,
		newDatasourceNetworkDnsRules,
		newDatasourceNetworkHostGroup,
		newDatasourceNetworkHostGroups,
		newDatasourceNetworkHost,
		newDatasourceNetworkHosts,
		newDatasourceNetworkImplicitDnsRule,
		newDatasourceNetworkImplicitDnsRules,
		newDatasourceNetworkWildcardFqdnCustom,
		newDatasourceNetworkWildcardFqdnCustoms,
		newDatasourcePrivateAccessNetworkConfiguration,
		newDatasourcePrivateAccessServiceConnection,
		newDatasourcePrivateAccessServiceConnections,
		newDatasourceSecurityAntivirusFiletype,
		newDatasourceSecurityAntivirusFiletypes,
		newDatasourceSecurityAntivirusProfile,
		newDatasourceSecurityAppCustomSignature,
		newDatasourceSecurityAppCustomSignatures,
		newDatasourceSecurityApplicationCategory,
		newDatasourceSecurityApplicationCategories,
		newDatasourceSecurityApplicationControlProfile,
		newDatasourceSecurityApplication,
		newDatasourceSecurityApplications,
		newDatasourceSecurityBotnetDomainsStat,
		newDatasourceSecurityCertLocalCaCert,
		newDatasourceSecurityCertLocalCaCerts,
		newDatasourceSecurityCertLocalCert,
		newDatasourceSecurityCertLocalCerts,
		newDatasourceSecurityCertRemoteCaCert,
		newDatasourceSecurityCertRemoteCaCerts,
		newDatasourceSecurityCertRemoteCert,
		newDatasourceSecurityCertRemoteCerts,
		newDatasourceSecurityDlpDataType,
		newDatasourceSecurityDlpDataTypes,
		newDatasourceSecurityDlpDictionary,
		newDatasourceSecurityDlpDictionaries,
		newDatasourceSecurityDlpExactDataMatch,
		newDatasourceSecurityDlpExactDataMatches,
		newDatasourceSecurityDlpFilePattern,
		newDatasourceSecurityDlpFilePatterns,
		newDatasourceSecurityDlpFingerprintDatabase,
		newDatasourceSecurityDlpFingerprintDatabases,
		newDatasourceSecurityDlpProfile,
		newDatasourceSecurityDlpSensor,
		newDatasourceSecurityDlpSensors,
		newDatasourceSecurityDnsFilterProfile,
		newDatasourceSecurityDomainThreatFeed,
		newDatasourceSecurityDomainThreatFeeds,
		newDatasourceSecurityEndpointToEndpointPolicy,
		newDatasourceSecurityEndpointToEndpointPolicies,
		newDatasourceSecurityFileFilterProfile,
		newDatasourceSecurityFortiguardCategory,
		newDatasourceSecurityFortiguardCategories,
		newDatasourceSecurityFortiguardLocalCategory,
		newDatasourceSecurityFortiguardLocalCategories,
		newDatasourceSecurityGeoipCountry,
		newDatasourceSecurityGeoipCountries,
		newDatasourceSecurityHtmlTemplate,
		newDatasourceSecurityHtmlTemplateImage,
		newDatasourceSecurityInternalPolicy,
		newDatasourceSecurityInternalPolicies,
		newDatasourceSecurityInternalProxyPolicy,
		newDatasourceSecurityInternalReversePolicy,
		newDatasourceSecurityInternalReversePolicies,
		newDatasourceSecurityIpThreatFeed,
		newDatasourceSecurityIpThreatFeeds,
		newDatasourceSecurityIpsCustomSignature,
		newDatasourceSecurityIpsCustomSignatures,
		newDatasourceSecurityIpsProfile,
		newDatasourceSecurityOnetimeSchedule,
		newDatasourceSecurityOnetimeSchedules,
		newDatasourceSecurityOutboundPolicy,
		newDatasourceSecurityOutboundPolicies,
		newDatasourceSecurityOutboundProxyPolicy,
		newDatasourceSecurityPerIpTrafficShaper,
		newDatasourceSecurityPkiUser,
		newDatasourceSecurityPkiUsers,
		newDatasourceSecurityProfileGroup,
		newDatasourceSecurityRecurringSchedule,
		newDatasourceSecurityRecurringSchedules,
		newDatasourceSecurityScheduleGroup,
		newDatasourceSecurityScheduleGroups,
		newDatasourceSecurityServiceCategory,
		newDatasourceSecurityServiceCategories,
		newDatasourceSecurityServiceGroup,
		newDatasourceSecurityServiceGroups,
		newDatasourceSecurityService,
		newDatasourceSecurityServices,
		newDatasourceSecuritySslSshProfile,
		newDatasourceSecurityTrafficShaper,
		newDatasourceSecurityTrafficShapingPolicy,
		newDatasourceSecurityUrlThreatFeed,
		newDatasourceSecurityUrlThreatFeeds,
		newDatasourceSecurityVideoFilterFortiguardCategory,
		newDatasourceSecurityVideoFilterFortiguardCategories,
		newDatasourceSecurityVideoFilterProfile,
		newDatasourceSecurityVideoFilterYoutubeKey,
		newDatasourceSecurityWebFilterProfile,
		newDatasourceUsageAuthFssoAgents,
		newDatasourceUsageAuthLdapServers,
		newDatasourceUsageAuthRadiusServers,
		newDatasourceUsageAuthUserGroups,
		newDatasourceUsageEndpointZtnaTags,
		newDatasourceUsageInfraSsids,
		newDatasourceUsageNetworkHostGroups,
		newDatasourceUsageNetworkHosts,
		newDatasourceUsageSecurityAppCustomSignatures,
		newDatasourceUsageSecurityDlpDictionaries,
		newDatasourceUsageSecurityDlpExactDataMatches,
		newDatasourceUsageSecurityDlpFilePatterns,
		newDatasourceUsageSecurityDlpFingerprintDatabases,
		newDatasourceUsageSecurityDlpSensors,
		newDatasourceUsageSecurityDomainThreatFeeds,
		newDatasourceUsageSecurityEndpointToEndpointPolicies,
		newDatasourceUsageSecurityFortiguardLocalCategories,
		newDatasourceUsageSecurityInternalPolicies,
		newDatasourceUsageSecurityInternalReversePolicies,
		newDatasourceUsageSecurityIpThreatFeeds,
		newDatasourceUsageSecurityIpsCustomSignatures,
		newDatasourceUsageSecurityOnetimeSchedules,
		newDatasourceUsageSecurityOutboundPolicies,
		newDatasourceUsageSecurityProfileGroup,
		newDatasourceUsageSecurityRecurringSchedules,
		newDatasourceUsageSecurityScheduleGroups,
		newDatasourceUsageSecurityServiceGroups,
		newDatasourceUsageSecurityServices,
		newDatasourceUsageSecurityUrlThreatFeeds,
	}
}

func New(version string) func() provider.Provider {
	return func() provider.Provider {
		return &FortisaseProvider{
			version: version,
		}
	}
}
